name: antitheft_tracker
description: A Flutter-based anti-theft tracker app
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Updated to match Flutter 3.27.3 (Dart 3.6.1)

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2 # Updated to latest stable
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.2 # Updated to latest stable
  geolocator: ^13.0.1 # Updated to latest stable
  flutter_dotenv: ^5.1.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  sensors_plus: ^5.0.1
  flutter_blue_plus: ^1.32.9 # Keep for BLE detection
  flutter_bluetooth_serial: ^0.4.0 # Keep for Bluetooth Classic (Android-only)
  device_info_plus: ^10.1.2 # Updated to latest stable
  jwt_decoder: ^2.0.1
  wifi_iot: ^0.3.18
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.5
  flutter_background_service: ^5.0.7
  # tflite_flutter: ^0.10.4 # Uncomment if needed for AIProtectionService
  # device_admin: ^0.0.3 # Uncomment if needed for Android admin features

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  uuid: ^4.5.0 # Updated to latest stable
  web_socket_channel: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - .env